### PR TITLE
Updated visualize() function

### PR DESCRIPTION
**Pull request by dassarthak18**
In the visualize() function, the traces_output.txt of the print() function which stored the information of all the nodes in the AnalysisTree alongside the networkx visualization has been removed. This hinders the readability of the visualization.

### CODE REVIEW

**Comment by crides** [comment]
Note: [this commit](https://github.com/AutoVerse-ai/Verse-library/commit/8dedf25b196754443c5a8bd44961ecbcb0872ca9) already removed these trace outputs. Also your current diff adds them back

**Comment by dassarthak18** [comment]
Yes, I'm aware. What I intended to say is that removing traces_output.txt hinders the readability of the output graph. For example, when we consider the visualize() output for lsync.py, we obtain a graph with only a single node with id = 0 (I am yet to understand why this is occurring) however looking at traces_output.txt we realize that there are in fact 17 nodes, all having the same node id, hence the output. The details of each node would be helpful in understanding the traces.

Figure_1
[traces_output.txt](https://github.com/AutoVerse-ai/Verse-library/files/11214328/traces_output.txt)

**Comment by crides** [comment]
Ah, sorry for my misunderstanding. We decided that this was not necessary as the `AnalysisTree` can be dumped to JSON already, and can be loaded back for future analysis if needed

**Comment by crides** [comment]
I'm not sure if this is what you are experiencing currently, but it could be that the `id` field was not set when loaded from json. this was fixed in 2057f98

**Comment by dassarthak18** [comment]
I think the traces_output.txt would be necessary in context of the graph output we are looking at, particularly for the lsync.py output I mentioned. I'm afraid that the id field not being set is not the source of error because I am looking at the latest code which includes the aforementioned commit.

**Pull request closed without merging**
